/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-07-22 08:35:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import user.model.vo.User;

public final class myPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("user.model.vo.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	User user = (User)request.getAttribute("user");

	//취미 : 하나의 문자열을 "," 로 각각 분리 처리
	String[] preferres = user.getPreferred().split(",");
	
	//checkbox 의 checked 속성 설정을 위한 배열 만듦
	String[] checked = new String[12];
	
	for(String preferred : preferres){
		switch(preferred){
		case "소설": checked[0] = "checked";  break;
		case "경제/경영": checked[1] = "checked";  break;
		case "자기계발": checked[2] = "checked";  break;
		case "시/에세이": checked[3] = "checked";  break;
		case "인문": checked[4] = "checked";  break;
		case "국어/외국어": checked[5] = "checked";  break;
		case "역사/풍속/신화": checked[6] = "checked";  break;
		case "사회/정치/법": checked[7] = "checked";  break;
		case "가정/생활/요리": checked[8] = "checked";  break;
		case "여행/취미": checked[9] = "checked";  break;
		case "건강/의학": checked[10] = "checked";  break;
		case "기타 장르": checked[11] = "checked";  break;
		}
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>북적북적</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/bookjeok/resources/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function validate(){\r\n");
      out.write("	var pwdValue = document.getElementById(\"upwd\").value;\r\n");
      out.write("	var pwdValue2 = document.getElementById(\"upwd2\").value;\r\n");
      out.write("	\r\n");
      out.write("	if(pwdValue !== pwdValue2){\r\n");
      out.write("		alert(\"암호와 암호확인의 값이 일치하지 않습니다.\");\r\n");
      out.write("		document.getElementById(\"upwd2\").value = \"\";\r\n");
      out.write("		document.getElementById(\"upwd\").select();\r\n");
      out.write("		return false;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	return true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function dupNickCheck(){\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url: \"/bookjeok/udupnickcheck\",\r\n");
      out.write("		type: \"post\",\r\n");
      out.write("		data: {nickname: $(\"#nickname\").val()},\r\n");
      out.write("		success: function(data){\r\n");
      out.write("			console.log(\"success : \" + data);\r\n");
      out.write("			if(data == \"ok\"){\r\n");
      out.write("				alert(\"사용 가능한 닉네임입니다.\");\r\n");
      out.write("				$(\"#usernm\").focus();\r\n");
      out.write("			}else{\r\n");
      out.write("				alert(\"이미 사용중인 닉네임입니다.\");\r\n");
      out.write("				$(\"#nickname\").select();\r\n");
      out.write("			}\r\n");
      out.write("		},\r\n");
      out.write("		error: function(jqXHR, textStatus, errorThrown){\r\n");
      out.write("			console.log(\"error : \" + jqXHR + \", \" \r\n");
      out.write("					+ textStatus + \", \" + errorThrown);\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	return false;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	table th { background-color: #8181F7; }\r\n");
      out.write("	table#outer { border: 2px solid #8181F7; }\r\n");
      out.write("	table input[type=submit] { background-color: #58ACFA; -webkit-border-radius: 10px; }\r\n");
      out.write("	table input[type=reset] { background-color: #58ACFA; -webkit-border-radius: 10px; }\r\n");
      out.write("	div { position: relative; float: left; }\r\n");
      out.write("	div#leftmenu {\r\n");
      out.write("		left: 400px;\r\n");
      out.write("		top: 175px;\r\n");
      out.write("	}\r\n");
      out.write("	div#leftmenu div#textdiv {\r\n");
      out.write("		align: center;\r\n");
      out.write("		background-color: #8181F7;\r\n");
      out.write("		width: 146px;\r\n");
      out.write("		height: 40px;\r\n");
      out.write("		-webkit-border-radius: 10px;\r\n");
      out.write("		border: 2px solid navy;\r\n");
      out.write("		font-size: 16pt;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		padding-top: 7px;\r\n");
      out.write("	}\r\n");
      out.write("	div#leftmenu input[type=button] {\r\n");
      out.write("		width: 150px;\r\n");
      out.write("		height: 35px;\r\n");
      out.write("		background-color: #58ACFA;\r\n");
      out.write("		-webkit-border-radius: 10px;\r\n");
      out.write("		font-color: white;\r\n");
      out.write("	}\r\n");
      out.write("	div#content {\r\n");
      out.write("		left: 420px;\r\n");
      out.write("	}\r\n");
      out.write("	div#content h1 img#teamlogo {\r\n");
      out.write("		width: 181px;\r\n");
      out.write("		height: 104px;\r\n");
      out.write("	}\r\n");
      out.write("	table#outer input[type=text] {\r\n");
      out.write("		width: 350px;\r\n");
      out.write("	}\r\n");
      out.write("	table#outer input[type=password] {\r\n");
      out.write("		width: 350px;\r\n");
      out.write("	}\r\n");
      out.write("	table#outer input[type=button] {\r\n");
      out.write("		background-color: #8181F7;\r\n");
      out.write("		-webkit-border-radius: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	table#outer input[type=email] {\r\n");
      out.write("		width: 350px;\r\n");
      out.write("	}\r\n");
      out.write("	table#outer input[type=textarea] {\r\n");
      out.write("		width: 350px;\r\n");
      out.write("		height: 50px;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div id=\"leftmenu\">\r\n");
      out.write("<table>\r\n");
      out.write("	<tr><td><div id=\"textdiv\">마이페이지</div></td></tr>\r\n");
      out.write("	<tr><td><input type=\"button\" value=\"프로필 수정\" onclick=\"javascript:location.href='logout';\"></td></tr>\r\n");
      out.write("	<tr><td><input type=\"button\" value=\"회원 정보 수정\" onclick=\"javascript:location.href='umypage?userid=");
      out.print( user.getUserId() );
      out.write("';\"></td></tr>\r\n");
      out.write("	<tr><td><input type=\"button\" value=\"회원 탈퇴\" onclick=\"javascript:location.href='uquitview?userid=");
      out.print( user.getUserId() );
      out.write("';\"></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"content\">\r\n");
      out.write("<center>\r\n");
      out.write("<h1 align=\"center\"><img src=\"/bookjeok/resources/bookjeok/bookjeok.png\" id=\"teamlogo\"></h1>\r\n");
      out.write("<br>\r\n");
      out.write("<form action=\"/bookjeok/uupdate\" method=\"post\" onsubmit=\"return validate();\">\r\n");
      out.write("<table id=\"outer\" align=\"center\" width=\"600\" cellspacing=\"5\" cellpadding=\"0\">\r\n");
      out.write("	<tr><th colspan=\"2\">회원정보</th></tr>\r\n");
      out.write("	<tr><th width=\"120\">아이디</th>\r\n");
      out.write("		<td><input type=\"text\" name=\"userid\" value=\"");
      out.print( user.getUserId() );
      out.write("\" readonly></td></tr>\r\n");
      out.write("	<tr><th width=\"120\">등 급</th>\r\n");
      out.write("		<td><input type=\"text\" name=\"userrank\" value=\"");
      out.print( user.getUserRank() );
      out.write("\" readonly></td></tr>\r\n");
      out.write("	<tr><th width=\"120\">포인트</th>\r\n");
      out.write("		<td><input type=\"text\" name=\"point\" value=\"");
      out.print( user.getPoint() );
      out.write("\" readonly></td></tr>\r\n");
      out.write("	<tr><th width=\"120\">암호</th>\r\n");
      out.write("		<td><input type=\"password\" name=\"userpwd\" id=\"upwd\" value=\"");
      out.print( user.getUserPwd() );
      out.write("\"></td></tr>\r\n");
      out.write("	<tr><th width=\"120\">암호확인</th>\r\n");
      out.write("		<td><input type=\"password\" id=\"upwd2\"></td></tr>\r\n");
      out.write("	<tr><th width=\"120\">닉네임</th>\r\n");
      out.write("		<td><input type=\"text\" name=\"nickname\" id=\"nickname\" value=\"");
      out.print( user.getNickName() );
      out.write("\"> &nbsp;\r\n");
      out.write("			<input type=\"button\" value=\"중복체크\" onclick=\"return dupNickCheck();\"></td></tr>\r\n");
      out.write("	<tr><th width=\"120\">이름</th>\r\n");
      out.write("		<td><input type=\"text\" name=\"usernm\" id=\"usernm\" value=\"");
      out.print( user.getUserNm() );
      out.write("\"></td></tr>\r\n");
      out.write("	<tr><th width=\"120\">나이</th>\r\n");
      out.write("		<td><input type=\"number\" name=\"age\" value=\"");
      out.print( user.getAge() );
      out.write("\"></td></tr>\r\n");
      out.write("	<tr><th width=\"120\">성별</th>\r\n");
      out.write("	<td>\r\n");
      out.write("		");
 if(user.getGender().equals("M")){ 
      out.write("\r\n");
      out.write("		<input type=\"radio\" name=\"gender\" value=\"M\" checked> 남자 &nbsp;\r\n");
      out.write("		<input type=\"radio\" name=\"gender\" value=\"F\"> 여자\r\n");
      out.write("		");
 }else{ 
      out.write("\r\n");
      out.write("		<input type=\"radio\" name=\"gender\" value=\"M\"> 남자 &nbsp;\r\n");
      out.write("		<input type=\"radio\" name=\"gender\" value=\"F\" checked> 여자\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("	</td></tr>\r\n");
      out.write("	<tr><th width=\"120\">전화번호</th>\r\n");
      out.write("		<td><input type=\"tel\" name=\"phone\" value=\"");
      out.print( user.getPhone() );
      out.write("\"> &nbsp;\r\n");
      out.write("			<input type=\"button\" value=\"인증 발송\"></td></tr>\r\n");
      out.write("	<tr><th width=\"120\">인증번호</th>\r\n");
      out.write("		<td><input type=\"text\" id=\"phoneDup\" style=\"width:170px;\"> &nbsp;\r\n");
      out.write("			<input type=\"button\" value=\"인증 확인\"></td></tr>\r\n");
      out.write("	<tr><th width=\"120\">이메일</th>\r\n");
      out.write("		<td><input type=\"email\" name=\"email\" value=\"");
      out.print( user.getEmail() );
      out.write("\"></td></tr>\r\n");
      out.write("	<tr><th width=\"120\">주소</th>\r\n");
      out.write("		<td><input type=\"text\" name=\"post\" value=\"\" style=\"width:170px;\">\r\n");
      out.write("			<input type=\"button\" value=\"우편번호 검색\"></td></tr>\r\n");
      out.write("	<tr><td></td>\r\n");
      out.write("		<td><input type=\"text\" name=\"addr\" value=\"");
      out.print( user.getAddr() );
      out.write("\"></td></tr>\r\n");
      out.write("	<tr><th width=\"120\">상세 주소</th>\r\n");
      out.write("		<td><input type=\"text\" name=\"addrdetail\" value=\"");
      out.print( user.getAddrDetail() );
      out.write("\"></td></tr>\r\n");
      out.write("	<tr><th width=\"120\">소 개</th>\r\n");
      out.write("		<td><textarea name=\"intro\" rows=\"3\" cols=\"48\">");
      out.print( user.getUserIntro() );
      out.write("</textarea></td></tr>\r\n");
      out.write("	<tr><th width=\"120\">선호 장르</th>\r\n");
      out.write("	<td>\r\n");
      out.write("		<table width=\"450\" >\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td><input type=\"checkbox\" name=\"preferred\" value=\"소설\" ");
      out.print( checked[0] );
      out.write("> 소설</td>\r\n");
      out.write("			<td><input type=\"checkbox\" name=\"preferred\" value=\"경제/경영\" ");
      out.print( checked[1] );
      out.write("> 경제/경영</td>\r\n");
      out.write("			<td><input type=\"checkbox\" name=\"preferred\" value=\"자기계발\" ");
      out.print( checked[2] );
      out.write("> 자기계발</td>\r\n");
      out.write("			<td><input type=\"checkbox\" name=\"preferred\" value=\"시/에세이\" ");
      out.print( checked[3] );
      out.write("> 시/에세이</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td><input type=\"checkbox\" name=\"preferred\" value=\"인문\" ");
      out.print( checked[4] );
      out.write("> 인문</td>\r\n");
      out.write("			<td><input type=\"checkbox\" name=\"preferred\" value=\"국어/외국어\" ");
      out.print( checked[5] );
      out.write("> 국어/외국어</td>\r\n");
      out.write("			<td><input type=\"checkbox\" name=\"preferred\" value=\"역사/풍속/신화\" ");
      out.print( checked[6] );
      out.write("> 역사/풍속/신화</td>\r\n");
      out.write("			<td><input type=\"checkbox\" name=\"preferred\" value=\"사회/정치/법\" ");
      out.print( checked[7] );
      out.write("> 사회/정치/법</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td><input type=\"checkbox\" name=\"preferred\" value=\"가정/생활/요리\" ");
      out.print( checked[8] );
      out.write("> 가정/생활/요리</td>\r\n");
      out.write("			<td><input type=\"checkbox\" name=\"preferred\" value=\"여행/취미\" ");
      out.print( checked[9] );
      out.write("> 여행/취미</td>\r\n");
      out.write("			<td><input type=\"checkbox\" name=\"preferred\" value=\"건강/의학\" ");
      out.print( checked[10] );
      out.write("> 건강/의학</td>\r\n");
      out.write("			<td><input type=\"checkbox\" name=\"preferred\" value=\"기타 장르\" ");
      out.print( checked[11] );
      out.write("> 기타 장르</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</td></tr>\r\n");
      out.write("	<tr height=\"35\"><th colspan=\"2\">\r\n");
      out.write("		<input type=\"submit\" value=\"수정하기\"> &nbsp; \r\n");
      out.write("		<input type=\"reset\" value=\"작성취소\"> &nbsp;\r\n");
      out.write("		<a href=\"/bookjeok/uquitview?userid=");
      out.print( user.getUserId() );
      out.write("\">탈퇴하기</a> &nbsp;\r\n");
      out.write("		<a href=\"javascript:history.go(-1);\">이전페이지로 이동</a>\r\n");
      out.write("	</th></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</center>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
