/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-07-30 13:03:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.usedshop;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import book.model.vo.Book;
import user.model.vo.User;

public final class auctionWriteView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/usedshop/../common/footer.jsp", Long.valueOf(1627539033020L));
    _jspx_dependants.put("/views/usedshop/../common/menubar.jsp", Long.valueOf(1627539010764L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("book.model.vo.Book");
    _jspx_imports_classes.add("user.model.vo.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	User auctionloginUser = (User) session.getAttribute("loginUser");
	Book book = (Book)request.getAttribute("book");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>북적북적</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".newautitle {\r\n");
      out.write("	color: #642EFE;\r\n");
      out.write("	margin-bottom: 0;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	left: -330px;\r\n");
      out.write("}\r\n");
      out.write(".booksearch {\r\n");
      out.write("	width: 120px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	background-color: #8258FA;\r\n");
      out.write("	-webkit-border-radius: 15px;\r\n");
      out.write("	border: 2px solid #642EFE;\r\n");
      out.write("	font-size: 14pt;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write(".searchtable {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	left: -230px;\r\n");
      out.write("}\r\n");
      out.write(".bookname {\r\n");
      out.write("	width: 220px;\r\n");
      out.write("	height: 35px;\r\n");
      out.write("	-webkit-border-radius: 10px;\r\n");
      out.write("	border: 1px solid black;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	font-size: 14pt;\r\n");
      out.write("	color: #8258FA;\r\n");
      out.write("}\r\n");
      out.write(".bookinfo {\r\n");
      out.write("	-webkit-border-radius: 10px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	margin-top: 15px;\r\n");
      out.write("	left: 100px;\r\n");
      out.write("}\r\n");
      out.write(".imgdiv {\r\n");
      out.write("	width: 220px;\r\n");
      out.write("	height: 280px;\r\n");
      out.write("	border: 2px solid #A9D0F5;\r\n");
      out.write("	-webkit-border-radius: 5px;\r\n");
      out.write("	float: left;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	left: 650px;\r\n");
      out.write("	top: 5px;\r\n");
      out.write("}\r\n");
      out.write(".eachtitle {\r\n");
      out.write("	border: 3px solid #8258FA;\r\n");
      out.write("	-webkit-border-radius: 10px;\r\n");
      out.write("	width: 120px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	margin-top: 0;\r\n");
      out.write("	margin-bottom: 0;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	color: white;\r\n");
      out.write("	background-color: #8181F7;\r\n");
      out.write("}\r\n");
      out.write(".eachcontent {\r\n");
      out.write("	margin-left: 3px;\r\n");
      out.write("	margin-top: 0;\r\n");
      out.write("	margin-bottom: 0;\r\n");
      out.write("	color: #8258FA;\r\n");
      out.write("}\r\n");
      out.write(".usedinfo {\r\n");
      out.write("	-webkit-border-radius: 10px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	margin-top: 15px;\r\n");
      out.write("}\r\n");
      out.write(".qualitytitle {\r\n");
      out.write("	margin-top: 0;\r\n");
      out.write("	margin-bottom: 0;\r\n");
      out.write("	border: 3px solid #8258FA;\r\n");
      out.write("	-webkit-border-radius: 10px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	color: white;\r\n");
      out.write("	background-color: #8181F7;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	width: 120px;\r\n");
      out.write("}\r\n");
      out.write(".usedquality {\r\n");
      out.write("	float: left;\r\n");
      out.write("	border: 2px solid #8258FA;\r\n");
      out.write("	-webkit-border-radius: 10px;\r\n");
      out.write("	color: #8258FA;\r\n");
      out.write("	width: 184px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	margin-right: 10px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-size: 14pt;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".infotitle {\r\n");
      out.write("	margin-top: 0;\r\n");
      out.write("	margin-bottom: 0;\r\n");
      out.write("	border: 3px solid #8258FA;\r\n");
      out.write("	-webkit-border-radius: 10px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	color: white;\r\n");
      out.write("	background-color: #8181F7;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	width: 120px;\r\n");
      out.write("}\r\n");
      out.write(".startbid {\r\n");
      out.write("	border: 3px solid #8258FA;\r\n");
      out.write("	-webkit-border-radius: 10px;\r\n");
      out.write("	height: 28px;\r\n");
      out.write("	width: 255px;\r\n");
      out.write("	font-size: 13pt;\r\n");
      out.write("	color: #8258FA;\r\n");
      out.write("}\r\n");
      out.write(".closedate {\r\n");
      out.write("	border: 3px solid #8258FA;\r\n");
      out.write("	-webkit-border-radius: 10px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	width: 255px;\r\n");
      out.write("	font-size: 13pt;\r\n");
      out.write("	color: #8258FA;\r\n");
      out.write("}\r\n");
      out.write(".usedintro {\r\n");
      out.write("	border: 3px solid #8258FA;\r\n");
      out.write("	-webkit-border-radius: 10px;\r\n");
      out.write("	font-size: 14pt;\r\n");
      out.write("	color: #8258FA;\r\n");
      out.write("}\r\n");
      out.write(".newnotice {\r\n");
      out.write("	color: #FE2E64;\r\n");
      out.write("}\r\n");
      out.write(".newauctionend {\r\n");
      out.write("	margin-top: 15px;\r\n");
      out.write("	margin-right: 30px;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("	border: 3px solid #8258FA;\r\n");
      out.write("	-webkit-border-radius: 15px;\r\n");
      out.write("	width: 140px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	font-size: 14pt;\r\n");
      out.write("	background-color: #5882FA;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\n');

	//로그인 확인을 위해서 내장된 session 객체를 이용
	User loginUser = (User) session.getAttribute("loginUser");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>북적북적</title>\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Serif+KR&display=swap\" rel=\"stylesheet\">\n");
      out.write("<style type=\"text/css\">\n");
      out.write("* { font-family: 'Noto Serif KR', serif; }\n");
      out.write(".imgtd {\n");
      out.write("	position: relative;\n");
      out.write("}\n");
      out.write(".teamlogo {\n");
      out.write("	width: 181px;\n");
      out.write("	height: 104px;\n");
      out.write("	position: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".bartd {\n");
      out.write("	position: relative;\n");
      out.write("	left: 260px;\n");
      out.write("}\n");
      out.write(".topbar {\n");
      out.write("	border: 2px solid #58ACFA;\n");
      out.write("	background-color: #58ACFA;\n");
      out.write("	-webkit-border-radius: 10px;\n");
      out.write("	color: white;\n");
      out.write("	position: relative;\n");
      out.write("}\n");
      out.write(".topbar td {\n");
      out.write("	border: 2px solid #2E64FE;\n");
      out.write("	background-color: #2E64FE;\n");
      out.write("	-webkit-border-radius: 10px;\n");
      out.write("	text-align: center;\n");
      out.write("}\n");
      out.write(".topbar td a {\n");
      out.write("	text-decoration: none;\n");
      out.write("	color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".admintopbar {\n");
      out.write("	border: 2px solid #58ACFA;\n");
      out.write("	background-color: #58ACFA;\n");
      out.write("	-webkit-border-radius: 10px;\n");
      out.write("	color: white;\n");
      out.write("	position: relative;\n");
      out.write("}\n");
      out.write(".admintopbar td {\n");
      out.write("	border: 2px solid #2E64FE;\n");
      out.write("	background-color: #2E64FE;\n");
      out.write("	-webkit-border-radius: 10px;\n");
      out.write("	text-align: center;\n");
      out.write("}\n");
      out.write(".admintopbar td a {\n");
      out.write("	text-decoration: none;\n");
      out.write("	color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".logintopbar {\n");
      out.write("	border: 2px solid #58ACFA;\n");
      out.write("	background-color: #58ACFA;\n");
      out.write("	-webkit-border-radius: 10px;\n");
      out.write("	color: white;\n");
      out.write("	position: relative;\n");
      out.write("}\n");
      out.write(".logintopbar td {\n");
      out.write("	border: 2px solid #2E64FE;\n");
      out.write("	background-color: #2E64FE;\n");
      out.write("	-webkit-border-radius: 5px;\n");
      out.write("	text-align: center;\n");
      out.write("}\n");
      out.write(".logintopbar td a {\n");
      out.write("	text-decoration: none;\n");
      out.write("	color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".mainbar {\n");
      out.write("	list-style: none;\n");
      out.write("	position: relative;\n");
      out.write("}\n");
      out.write(".mainbar li {\n");
      out.write("	float: left;\n");
      out.write("	width: 180px;\n");
      out.write("	height: 40px;\n");
      out.write("	margin-right: 5px;\n");
      out.write("	padding: 0;\n");
      out.write("	font-size : 20pt;\n");
      out.write("}\n");
      out.write(".mainbar li a {\n");
      out.write("	text-decoration: none;\n");
      out.write("	width: 180px;\n");
      out.write("	height: 50px;\n");
      out.write("	display: block;\n");
      out.write("	background: #8181F7;\n");
      out.write("	color: navy;\n");
      out.write("	text-align: center;\n");
      out.write("	font-weight: bold;\n");
      out.write("	margin: 0;\n");
      out.write("	text-shadow: 1px 1px 2px white;\n");
      out.write("	padding-top: 5px;\n");
      out.write("	-webkit-border-radius: 10px;\n");
      out.write("	border: 2px solid #5858FA;\n");
      out.write("}\n");
      out.write(".mainbar li a:hover {\n");
      out.write("	text-decoration: none;\n");
      out.write("	width: 180px;\n");
      out.write("	height: 50px;\n");
      out.write("	display: block;\n");
      out.write("	background: #2E2EFE;\n");
      out.write("	color: white;\n");
      out.write("	text-align: center;\n");
      out.write("	font-weight: bold;\n");
      out.write("	margin: 0;\n");
      out.write("	text-shadow: 1px 1px 2px navy;\n");
      out.write("	padding-top: 5px;\n");
      out.write("	-webkit-border-radius: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".adminmainbar {\n");
      out.write("	list-style: none;\n");
      out.write("	position: relative;\n");
      out.write("	/* top: -30px; */\n");
      out.write("}\n");
      out.write(".adminmainbar li {\n");
      out.write("	width: 150px;\n");
      out.write("	height: 40px;\n");
      out.write("	margin-right: 5px;\n");
      out.write("	padding: 0;\n");
      out.write("	font-size : 18pt;\n");
      out.write("}\n");
      out.write(".admmbutton {\n");
      out.write("	text-decoration: none;\n");
      out.write("	width: 150px;\n");
      out.write("	height: 55px;\n");
      out.write("	display: block;\n");
      out.write("	background: #8181F7;\n");
      out.write("	color: navy;\n");
      out.write("	font-size: 18pt;\n");
      out.write("	text-align: center;\n");
      out.write("	font-weight: bold;\n");
      out.write("	margin: 0;\n");
      out.write("	text-shadow: 1px 1px 2px white;\n");
      out.write("	padding-top: 5px;\n");
      out.write("	-webkit-border-radius: 10px;\n");
      out.write("	border: 2px solid #5858FA;\n");
      out.write("	cursor: pointer;\n");
      out.write("}\n");
      out.write(".mainbar input.admmbutton[type=\"button\"]:hover {\n");
      out.write("	text-decoration: none;\n");
      out.write("	width: 150px;\n");
      out.write("	height: 55px;\n");
      out.write("	display: block;\n");
      out.write("	background: #2E2EFE;\n");
      out.write("	color: white;\n");
      out.write("	text-align: center;\n");
      out.write("	font-weight: bold;\n");
      out.write("	margin: 0;\n");
      out.write("	text-shadow: 1px 1px 2px navy;\n");
      out.write("	padding-top: 5px;\n");
      out.write("	-webkit-border-radius: 10px;\n");
      out.write("}\n");
      out.write(".mmbutton {\n");
      out.write("	text-decoration: none;\n");
      out.write("	width: 180px;\n");
      out.write("	height: 55px;\n");
      out.write("	display: block;\n");
      out.write("	background: #8181F7;\n");
      out.write("	font-size: 18pt;\n");
      out.write("	color: navy;\n");
      out.write("	text-align: center;\n");
      out.write("	font-weight: bold;\n");
      out.write("	margin: 0;\n");
      out.write("	text-shadow: 1px 1px 2px white;\n");
      out.write("	padding-top: 5px;\n");
      out.write("	-webkit-border-radius: 10px;\n");
      out.write("	border: 2px solid #5858FA;\n");
      out.write("}\n");
      out.write("hr {\n");
      out.write("	clear: both;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<center>\n");
      out.write("<table width=\"900\">\n");
      out.write("	<tr>\n");
      out.write("		<td class=\"imgtd\"><img class=\"teamlogo\" src=\"/bookjeok/resources/bookjeok/bookjeok.png\" onclick=\"javascript:location.href='/bookjeok/index.jsp'\"></td>\n");
      out.write("		<td class=\"bartd\">\n");
      out.write("		");
 if (loginUser == null) { 
      out.write("\n");
      out.write("		<table class=\"topbar\">\n");
      out.write("			<tr><td><a href=\"/bookjeok/nlist\">공지사항</td>\n");
      out.write("				<td><a href=\"/bookjeok/alist\">1:1 문의</a></td>\n");
      out.write("				<td><a href=\"/bookjeok/views/user/loginPage.jsp\">로그인</a></td></tr>\n");
      out.write("		</table>\n");
      out.write("		");
 } else if (loginUser != null && loginUser.getAdmin().equals("Y")) { 
      out.write("\n");
      out.write("		<table class=\"admintopbar\">\n");
      out.write("		<tr><td>");
      out.print(loginUser.getUserId());
      out.write("님</td>\n");
      out.write("			<td><a href=\"/bookjeok/ulogout\">로그아웃</td></tr>\n");
      out.write("		</table>\n");
      out.write("		");
 } else if (loginUser != null) { 
      out.write("\n");
      out.write("		<table class=\"logintopbar\">\n");
      out.write("			<tr><td><a href=\"/bookjeok/nlist\">공지사항</td>\n");
      out.write("				<td><a href=\"/bookjeok/alist\">1:1 문의</a></td>\n");
      out.write("				<td>");
      out.print(loginUser.getUserId());
      out.write("님</a></td></tr>\n");
      out.write("			<tr><th></th>\n");
      out.write("				<td><a href=\"/bookjeok/umyprofile?userid=");
      out.print(loginUser.getUserId());
      out.write("\">마이페이지</a></td>\n");
      out.write("				<td><a href=\"/bookjeok/ulogout\">로그아웃</a></td></tr>\n");
      out.write("		</table>\n");
      out.write("		");
 } 
      out.write("\n");
      out.write("		<br>\n");
      out.write("		</td>\n");
      out.write("	</tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
 if (loginUser == null) { 
      out.write("\n");
      out.write("<table class=\"mainbar\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("	<tr>\n");
      out.write("		<td><input type=\"button\" class=\"mmbutton\" value=\"도서\" onclick=\"javascript:location.href='/bookjeok/views/book/PBookMainView.jsp';\"></td>\n");
      out.write("		<td><input type=\"button\" class=\"mmbutton\" value=\"E-Book\" onclick=\"javascript:location.href='/bookjeok/views/book/EBookMainView.jsp';\"></td>\n");
      out.write("		<td><input type=\"button\" class=\"mmbutton\" value=\"오디오북\" onclick=\"javascript:location.href='/bookjeok/views/book/ABookMainView.jsp';\"></td>\n");
      out.write("		<td><input type=\"button\" class=\"mmbutton\" value=\"중고장터\" onclick=\"javascript:location.href='/bookjeok/views/usedshop/UsedShopMainView.jsp';\"></td>\n");
      out.write("		<td><input type=\"button\" class=\"mmbutton\" value=\"리뷰\" onclick=\"javascript:location.href='/bookjeok/views/review/ReviewMainView.jsp';\"></td>\n");
      out.write("	</tr>\n");
      out.write("</table>\n");
 } else if (loginUser != null && loginUser.getAdmin().equals("Y")) { 
      out.write("\n");
      out.write("<table class=\"adminmainbar\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("	<tr>\n");
      out.write("		<td><input type=\"button\" class=\"admmbutton\" value=\"회원관리\" onclick=\"javascript:location.href='/bookjeok/ulist.ad';\"></td>\n");
      out.write("		<td><input type=\"button\" class=\"admmbutton\" value=\"상품관리\" onclick=\"javascript:location.href='';\"></td>\n");
      out.write("		<td><input type=\"button\" class=\"admmbutton\" value=\"장터관리\" onclick=\"javascript:location.href='';\"></td>\n");
      out.write("		<td><input type=\"button\" class=\"admmbutton\" value=\"장터관리\" onclick=\"javascript:location.href='';\"></td>\n");
      out.write("		<td><input type=\"button\" class=\"admmbutton\" value=\"공지사항관리\" onclick=\"javascript:location.href='';\"></td>\n");
      out.write("		<td><input type=\"button\" class=\"admmbutton\" value=\"1:1 문의관리\" onclick=\"javascript:location.href='';\"></td>\n");
      out.write("	</tr>\n");
      out.write("</table>\n");
 } else if (loginUser != null) { 
      out.write("\n");
      out.write("<table class=\"mainbar\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("	<tr>\n");
      out.write("		<td><input type=\"button\" class=\"mmbutton\" value=\"도서\" onclick=\"javascript:location.href='/bookjeok/views/book/PBookMainView.jsp';\"></td>\n");
      out.write("		<td><input type=\"button\" class=\"mmbutton\" value=\"E-Book\" onclick=\"javascript:location.href='/bookjeok/views/book/EBookMainView.jsp';\"></td>\n");
      out.write("		<td><input type=\"button\" class=\"mmbutton\" value=\"오디오북\" onclick=\"javascript:location.href='/bookjeok/views/book/ABookMainView.jsp';\"></td>\n");
      out.write("		<td><input type=\"button\" class=\"mmbutton\" value=\"중고장터\" onclick=\"javascript:location.href='/bookjeok/views/usedshop/UsedShopMainView.jsp';\"></td>\n");
      out.write("		<td><input type=\"button\" class=\"mmbutton\" value=\"리뷰\" onclick=\"javascript:location.href='/bookjeok/views/review/ReviewMainView.jsp';\"></td>\n");
      out.write("	</tr>\n");
      out.write("</table>\n");
 } 
      out.write("\n");
      out.write("</center>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h1 class=\"newautitle\" align=\"center\">경매 등록</h1>\r\n");
      out.write("<br>\r\n");
      out.write("<table align=\"center\" class=\"searchtable\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><input type=\"button\" class=\"booksearch\" name=\"booksearch\" value=\"도서검색\" \r\n");
      out.write("				onclick=\"window.open('/bookjeok/views/usedshop/usedshopBookSearch.jsp', \r\n");
      out.write("					'searchWindow', 'width=350, height=200, scrollbars=no, resizable=no, status=no, menubar=no, toolbar=no');\"></td>\r\n");
      out.write("		<td><input type=\"text\" class=\"bookname\" name=\"bookname\" value=\" ");
      out.print( book.getBookNm() );
      out.write(' ');
      out.write('"');
      out.print( book.getBookNm() );
      out.write(" readonly></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<form action=\"/bookjeok/usauwrite\" method=\"post\" onsubmit=\"return validate();\">\r\n");
      out.write("<input type=\"hidden\" name=\"writerid\" value=\"");
      out.print( auctionloginUser.getUserId() );
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"usedbookid\" value=\"");
      out.print( book.getBookId() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("<div class=\"imgdiv\">\r\n");
      out.write("	<img width=\"240px\" class=\"bookimg\" width=\"100%\" src=\"/bookjeok/resources/book_img/' + ");
      out.print( book.getBookNm() );
      out.write(" + '.png\">\r\n");
      out.write("</div>\r\n");
      out.write("<table class=\"bookinfo\" align=\"center\" width=\"400\" cellspacing=\"5\" cellpadding=\"0\">\r\n");
      out.write("	<tr><td width=\"120px\"><h3 class=\"eachtitle\">도서명</h3></td>\r\n");
      out.write("		<td><h3 class=\"eachcontent\">");
      out.print( book.getBookNm() );
      out.write("</h3></td></tr>\r\n");
      out.write("	<tr><td><h3 class=\"eachtitle\">ISBN</h3></td>\r\n");
      out.write("		<td><h3 class=\"eachcontent\">");
      out.print( book.getIsbn() );
      out.write("</h3></td></tr>\r\n");
      out.write("	<tr><td><h3 class=\"eachtitle\">도서분류</h3></td>\r\n");
      out.write("		<td><h3 class=\"eachcontent\">");
      out.print( book.getBookCategory() );
      out.write("</h3></td></tr>\r\n");
      out.write("	<tr><td><h3 class=\"eachtitle\">저 자</h3></td>\r\n");
      out.write("		<td><h3 class=\"eachcontent\">");
      out.print( book.getAuthor() );
      out.write("</h3></td></tr>\r\n");
      out.write("	<tr><td><h3 class=\"eachtitle\">출판사</h3></td>\r\n");
      out.write("		<td><h3 class=\"eachcontent\">");
      out.print( book.getPublisher() );
      out.write("</h3></td></tr>\r\n");
      out.write("	<tr><td><h3 class=\"eachtitle\">출판날짜</h3></td>\r\n");
      out.write("		<td><h3 class=\"eachcontent\">");
      out.print( book.getPublishDate() );
      out.write("</h3></td></tr>\r\n");
      out.write("	<tr><td><h3 class=\"eachtitle\">정 가</h3></td>\r\n");
      out.write("		<td><h3 class=\"eachcontent\">");
      out.print( book.getBookPrice() );
      out.write("</h3></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table class=\"usedinfo\" align=\"center\" width=\"800\" cellspacing=\"5\" cellpadding=\"0\">\r\n");
      out.write("	<tr><td colspan=\"4\"><h3 class=\"qualitytitle\">품 질</h3></td></tr>\r\n");
      out.write("	<tr><td colspan=\"4\" style=\"padding-left: 3px\">\r\n");
      out.write("			<div class=\"usedquality\"><input type=\"radio\" name=\"usedquality\" value=\"S\" required>S 급</div>\r\n");
      out.write("			<div class=\"usedquality\"><input type=\"radio\" name=\"usedquality\" value=\"A\" required>A 급</div>\r\n");
      out.write("			<div class=\"usedquality\"><input type=\"radio\" name=\"usedquality\" value=\"B\" required>B 급</div>\r\n");
      out.write("			<div class=\"usedquality\"><input type=\"radio\" name=\"usedquality\" value=\"C\" required>C 급</div>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr><th width=\"120px\"><h3 class=\"infotitle\">입찰 시작가</h3></th>\r\n");
      out.write("		<td width=\"265px\"><input type=\"number\" class=\"startbid\" name=\"startbid\" required></td>\r\n");
      out.write("		<th width=\"120px\"><h3 class=\"infotitle\">마감 날짜</h3></th>\r\n");
      out.write("		<td><input type=\"date\" class=\"closedate\" name=\"closedate\" required></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr><th colspan=\"4\" align=\"left\"><h3 class=\"infotitle\">상품 소개</h3></th></tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td colspan=\"4\">\r\n");
      out.write("			<textarea rows=\"7\" cols=\"70\" class=\"usedintro\" name=\"usedintro\"></textarea>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</center>\r\n");
      out.write("<center>\r\n");
      out.write("<h3 class=\"newnotice\" style=\"margin-bottom: 0px;\">경매는 등록하면 정보를 바꿀 수 없습니다.</h3>\r\n");
      out.write("<h3 class=\"newnotice\" style=\"margin-top: 0px; margin-bottom: 5px;\">허위 매물이 되지 않도록, 신중히 작성해주세요.</h3>\r\n");
      out.write("<input type=\"submit\" class=\"newauctionend\" value=\"등록하기\">\r\n");
      out.write("<input type=\"reset\" class=\"newauctionend\" value=\"취소하기\">\r\n");
      out.write("</center>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>북적북적</title>\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Serif+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("* { font-family: 'Noto Serif KR', serif; }\r\n");
      out.write("\r\n");
      out.write("div#footer {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	bottom: 0;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	color: #01DF3A;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("copyright@ict.org &nbsp; 자바,파이썬 기반 빅데이터 플랫폼 개발자 양성과정<br>\r\n");
      out.write("서울시 마포구 서교동 첨단빌딩 7층, TEL : 02-1234-5678, \r\n");
      out.write("FAX : 02-1234-5679\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
