/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-08-09 05:45:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.usedshop;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import usedshop.model.vo.UsedShopAuctionSelect;
import user.model.vo.User;
import user.model.vo.User;

public final class UsedShopAuctionDetailView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/usedshop/../common/footer.jsp", Long.valueOf(1627539033020L));
    _jspx_dependants.put("/views/usedshop/../common/usedshopAuctionTopMenu.jsp", Long.valueOf(1628482911767L));
    _jspx_dependants.put("/views/usedshop/../common/menubar.jsp", Long.valueOf(1628431535259L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("usedshop.model.vo.UsedShopAuctionSelect");
    _jspx_imports_classes.add("user.model.vo.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	UsedShopAuctionSelect usauselect = (UsedShopAuctionSelect)request.getAttribute("usauselect");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>북적북적</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".contentbox {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	left: 80px;\r\n");
      out.write("	top: -970px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("	border: 3px solid #5F04B4;\r\n");
      out.write("	-webkit-border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write(".usimg {\r\n");
      out.write("	width: 210px;\r\n");
      out.write("	margin-bottom: 25px;\r\n");
      out.write("}\r\n");
      out.write(".usinfo {\r\n");
      out.write("	-webkit-border-radius: 10px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	margin-top: 15px;\r\n");
      out.write("}\r\n");
      out.write(".eachtitle {\r\n");
      out.write("	border: 3px solid #8258FA;\r\n");
      out.write("	-webkit-border-radius: 10px;\r\n");
      out.write("	width: 120px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	margin-top: 0;\r\n");
      out.write("	margin-bottom: 0;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	color: white;\r\n");
      out.write("	background-color: #8181F7;\r\n");
      out.write("}\r\n");
      out.write(".eachcontent {\r\n");
      out.write("	margin-left: 5px;\r\n");
      out.write("	margin-top: 0;\r\n");
      out.write("	margin-bottom: 0;\r\n");
      out.write("	color: #8258FA;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("}\r\n");
      out.write(".usedintro {\r\n");
      out.write("	margin-top: 0;\r\n");
      out.write("	margin-bottom: 0;\r\n");
      out.write("	color: #8258FA;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("	border: 3px solid #8258FA;\r\n");
      out.write("	-webkit-border-radius: 10px;\r\n");
      out.write("	padding-left: 5px;\r\n");
      out.write("	height: 120px;\r\n");
      out.write("}\r\n");
      out.write(".ususerbid {\r\n");
      out.write("	width: 120px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-size: 13pt;\r\n");
      out.write("	color: white;\r\n");
      out.write("	border: 2px solid #8181F7;\r\n");
      out.write("	background-color: #58ACFA;\r\n");
      out.write("	-webkit-border-radius: 10px;\r\n");
      out.write("	margin-top: 15px;\r\n");
      out.write("}\r\n");
      out.write(".ussystembid {\r\n");
      out.write("	width: 120px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-size: 13pt;\r\n");
      out.write("	color: white;\r\n");
      out.write("	border: 2px solid #8181F7;\r\n");
      out.write("	background-color: #58ACFA;\r\n");
      out.write("	-webkit-border-radius: 10px;\r\n");
      out.write("	margin-top: 15px;\r\n");
      out.write("}\r\n");
      out.write(".updateend {\r\n");
      out.write("	width: 120px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-size: 13pt;\r\n");
      out.write("	color: white;\r\n");
      out.write("	border: 2px solid #8181F7;\r\n");
      out.write("	background-color: #58ACFA;\r\n");
      out.write("	-webkit-border-radius: 10px;\r\n");
      out.write("	margin-top: 15px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\n');

	//로그인 확인을 위해서 내장된 session 객체를 이용
	User loginUser = (User) session.getAttribute("loginUser");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>북적북적</title>\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Serif+KR&display=swap\" rel=\"stylesheet\">\n");
      out.write("<style type=\"text/css\">\n");
      out.write("* { font-family: 'Noto Serif KR', serif; }\n");
      out.write(".imgtd {\n");
      out.write("	position: relative;\n");
      out.write("}\n");
      out.write(".teamlogo {\n");
      out.write("	width: 181px;\n");
      out.write("	height: 104px;\n");
      out.write("	position: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".bartd {\n");
      out.write("	position: relative;\n");
      out.write("	left: 260px;\n");
      out.write("}\n");
      out.write(".topbar {\n");
      out.write("	border: 2px solid #8181F7;\n");
      out.write("	background-color: #8181F7;\n");
      out.write("	-webkit-border-radius: 10px;\n");
      out.write("	color: white;\n");
      out.write("	position: relative;\n");
      out.write("}\n");
      out.write(".topbar td {\n");
      out.write("	border: 2px solid #8181F7;\n");
      out.write("	background-color: #8181F7;\n");
      out.write("	-webkit-border-radius: 10px;\n");
      out.write("	text-align: center;\n");
      out.write("}\n");
      out.write(".topbar td a {\n");
      out.write("	text-decoration: none;\n");
      out.write("	color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".admintopbar {\n");
      out.write("	border: 2px solid #8181F7;\n");
      out.write("	background-color: #8181F7;\n");
      out.write("	-webkit-border-radius: 10px;\n");
      out.write("	color: white;\n");
      out.write("	position: relative;\n");
      out.write("}\n");
      out.write(".admintopbar td {\n");
      out.write("	border: 2px solid #8181F7;\n");
      out.write("	background-color: #8181F7;\n");
      out.write("	-webkit-border-radius: 10px;\n");
      out.write("	text-align: center;\n");
      out.write("}\n");
      out.write(".admintopbar td a {\n");
      out.write("	text-decoration: none;\n");
      out.write("	color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".logintopbar {\n");
      out.write("	border: 2px solid #8181F7;\n");
      out.write("	background-color: #8181F7;\n");
      out.write("	-webkit-border-radius: 10px;\n");
      out.write("	color: white;\n");
      out.write("	position: relative;\n");
      out.write("}\n");
      out.write(".logintopbar td {\n");
      out.write("	border: 2px solid #8181F7;\n");
      out.write("	background-color: #8181F7;\n");
      out.write("	-webkit-border-radius: 5px;\n");
      out.write("	text-align: center;\n");
      out.write("}\n");
      out.write(".logintopbar td a {\n");
      out.write("	text-decoration: none;\n");
      out.write("	color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".mainbar {\n");
      out.write("	list-style: none;\n");
      out.write("	position: relative;\n");
      out.write("}\n");
      out.write(".mainbar li {\n");
      out.write("	float: left;\n");
      out.write("	width: 180px;\n");
      out.write("	height: 40px;\n");
      out.write("	margin-right: 5px;\n");
      out.write("	padding: 0;\n");
      out.write("	font-size : 20pt;\n");
      out.write("}\n");
      out.write(".mainbar li a {\n");
      out.write("	text-decoration: none;\n");
      out.write("	width: 180px;\n");
      out.write("	height: 50px;\n");
      out.write("	display: block;\n");
      out.write("	background: #8181F7;\n");
      out.write("	color: navy;\n");
      out.write("	text-align: center;\n");
      out.write("	font-weight: bold;\n");
      out.write("	margin: 0;\n");
      out.write("	text-shadow: 1px 1px 2px white;\n");
      out.write("	padding-top: 5px;\n");
      out.write("	-webkit-border-radius: 10px;\n");
      out.write("	border: 2px solid #5858FA;\n");
      out.write("}\n");
      out.write(".mainbar li a:hover {\n");
      out.write("	text-decoration: none;\n");
      out.write("	width: 180px;\n");
      out.write("	height: 50px;\n");
      out.write("	display: block;\n");
      out.write("	background: #2E2EFE;\n");
      out.write("	color: white;\n");
      out.write("	text-align: center;\n");
      out.write("	font-weight: bold;\n");
      out.write("	margin: 0;\n");
      out.write("	text-shadow: 1px 1px 2px navy;\n");
      out.write("	padding-top: 5px;\n");
      out.write("	-webkit-border-radius: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".adminmainbar {\n");
      out.write("	list-style: none;\n");
      out.write("	position: relative;\n");
      out.write("	/* top: -30px; */\n");
      out.write("}\n");
      out.write(".adminmainbar li {\n");
      out.write("	width: 150px;\n");
      out.write("	height: 40px;\n");
      out.write("	margin-right: 5px;\n");
      out.write("	padding: 0;\n");
      out.write("	font-size : 18pt;\n");
      out.write("}\n");
      out.write(".admmbutton {\n");
      out.write("	text-decoration: none;\n");
      out.write("	width: 150px;\n");
      out.write("	height: 55px;\n");
      out.write("	display: block;\n");
      out.write("	background: #8181F7;\n");
      out.write("	color: navy;\n");
      out.write("	font-size: 18pt;\n");
      out.write("	text-align: center;\n");
      out.write("	font-weight: bold;\n");
      out.write("	margin: 0;\n");
      out.write("	text-shadow: 1px 1px 2px white;\n");
      out.write("	padding-top: 5px;\n");
      out.write("	-webkit-border-radius: 10px;\n");
      out.write("	border: 2px solid #5858FA;\n");
      out.write("	cursor: pointer;\n");
      out.write("}\n");
      out.write(".mainbar input.mmbutton[type=\"button\"]:hover {\n");
      out.write("	text-decoration: none;\n");
      out.write("	width: 180px;\n");
      out.write("	height: 55px;\n");
      out.write("	display: block;\n");
      out.write("	background: #2E2EFE;\n");
      out.write("	color: white;\n");
      out.write("	text-align: center;\n");
      out.write("	font-weight: bold;\n");
      out.write("	margin: 0;\n");
      out.write("	text-shadow: 1px 1px 2px navy;\n");
      out.write("	padding-top: 5px;\n");
      out.write("	-webkit-border-radius: 10px;\n");
      out.write("}\n");
      out.write(".adminmainbar input.admmbutton[type=\"button\"]:hover {\n");
      out.write("	text-decoration: none;\n");
      out.write("	width: 150px;\n");
      out.write("	height: 55px;\n");
      out.write("	display: block;\n");
      out.write("	background: #2E2EFE;\n");
      out.write("	color: white;\n");
      out.write("	text-align: center;\n");
      out.write("	font-weight: bold;\n");
      out.write("	margin: 0;\n");
      out.write("	text-shadow: 1px 1px 2px navy;\n");
      out.write("	padding-top: 5px;\n");
      out.write("	-webkit-border-radius: 10px;\n");
      out.write("}\n");
      out.write(".mmbutton {\n");
      out.write("	text-decoration: none;\n");
      out.write("	width: 180px;\n");
      out.write("	height: 55px;\n");
      out.write("	display: block;\n");
      out.write("	background: #8181F7;\n");
      out.write("	font-size: 18pt;\n");
      out.write("	color: navy;\n");
      out.write("	text-align: center;\n");
      out.write("	font-weight: bold;\n");
      out.write("	margin: 0;\n");
      out.write("	text-shadow: 1px 1px 2px white;\n");
      out.write("	padding-top: 5px;\n");
      out.write("	-webkit-border-radius: 10px;\n");
      out.write("	border: 2px solid #5858FA;\n");
      out.write("}\n");
      out.write("hr {\n");
      out.write("	clear: both;\n");
      out.write("}\n");
      out.write(".logintopbar .dropbtn {\n");
      out.write("  background-color: #8181F7;\n");
      out.write("  color: white;\n");
      out.write("  font-size: 16px;\n");
      out.write("  border: none;\n");
      out.write("  height: 25px;\n");
      out.write("}\n");
      out.write(".logintopbar .dropdown {\n");
      out.write("  position: relative;\n");
      out.write("  display: inline-block;\n");
      out.write("}\n");
      out.write(".logintopbar .dropdown-content {\n");
      out.write("  display: none;\n");
      out.write("  position: absolute;\n");
      out.write("  background-color: #8181F7;\n");
      out.write("  min-width: 120px;\n");
      out.write("  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);\n");
      out.write("  z-index: 1;\n");
      out.write("  left: -40px;\n");
      out.write("	-webkit-border-radius: 10px;\n");
      out.write("	border: 2px solid #5858FA;\n");
      out.write("}\n");
      out.write(".logintopbar .dropdown-content a {\n");
      out.write("  color: black;\n");
      out.write("  padding: 12px 16px;\n");
      out.write("  text-decoration: none;\n");
      out.write("  display: block;\n");
      out.write("  color: white;\n");
      out.write("}\n");
      out.write(".logintopbar .dropdown-content a:hover {\n");
      out.write("	background-color: #2E2EFE;\n");
      out.write("	-webkit-border-radius: 10px;\n");
      out.write("}\n");
      out.write(".logintopbar .dropdown:hover .dropdown-content {display: block;}\n");
      out.write(".logintopbar .dropdown:hover .dropbtn {\n");
      out.write("	background-color: #2E2EFE;\n");
      out.write("	-webkit-border-radius: 10px;\n");
      out.write("}\n");
      out.write(".dropdown {\n");
      out.write("	height: 10px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<center>\n");
      out.write("<table width=\"900\">\n");
      out.write("	<tr>\n");
      out.write("		<td class=\"imgtd\"><img class=\"teamlogo\" src=\"/bookjeok/resources/bookjeok/bookjeok.png\" onclick=\"javascript:location.href='/bookjeok/index.jsp'\"></td>\n");
      out.write("		<td class=\"bartd\">\n");
      out.write("		");
 if (loginUser == null) { 
      out.write("\n");
      out.write("		<table class=\"topbar\">\n");
      out.write("			<tr><td><a href=\"/bookjeok/nlist\">공지사항</td>\n");
      out.write("				<td><a href=\"/bookjeok/alist\">1:1 문의</a></td>\n");
      out.write("				<td><a href=\"/bookjeok/views/user/loginPage.jsp\">로그인</a></td></tr>\n");
      out.write("		</table>\n");
      out.write("		");
 } else if (loginUser != null && loginUser.getAdmin().equals("Y")) { 
      out.write("\n");
      out.write("		<table class=\"admintopbar\">\n");
      out.write("		<tr><td>");
      out.print(loginUser.getNickName());
      out.write("님</td>\n");
      out.write("			<td><a href=\"/bookjeok/ulogout\">로그아웃</td></tr>\n");
      out.write("		</table>\n");
      out.write("		");
 } else if (loginUser != null) { 
      out.write("\n");
      out.write("		<table class=\"logintopbar\">\n");
      out.write("			<tr><td><a href=\"/bookjeok/nlist\">공지사항</td>\n");
      out.write("				<td><a href=\"/bookjeok/alist\">1:1 문의</a></td>\n");
      out.write("				<td><div class=\"dropdown\">\n");
      out.write("					<button class=\"dropbtn\">");
      out.print(loginUser.getNickName());
      out.write("님</button>\n");
      out.write("						<div class=\"dropdown-content\">\n");
      out.write("								<a href=\"/bookjeok/umyprofile?userid=");
      out.print(loginUser.getUserId());
      out.write("\">마이페이지</a>\n");
      out.write("								<a href=\"/bookjeok/ulogout\">로그아웃</a>\n");
      out.write("						</div>\n");
      out.write("					</div></td></tr>\n");
      out.write("		</table>\n");
      out.write("		");
 } 
      out.write("\n");
      out.write("		<br>\n");
      out.write("		</td>\n");
      out.write("	</tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
 if (loginUser == null) { 
      out.write("\n");
      out.write("<table class=\"mainbar\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("	<tr>\n");
      out.write("		<td><input type=\"button\" class=\"mmbutton\" value=\"도서\" onclick=\"javascript:location.href='/bookjeok/views/book/PBookMainView.jsp';\"></td>\n");
      out.write("		<td><input type=\"button\" class=\"mmbutton\" value=\"E-Book\" onclick=\"javascript:location.href='/bookjeok/views/book/EBookMainView.jsp';\"></td>\n");
      out.write("		<td><input type=\"button\" class=\"mmbutton\" value=\"오디오북\" onclick=\"javascript:location.href='/bookjeok/views/book/ABookMainView.jsp';\"></td>\n");
      out.write("		<td><input type=\"button\" class=\"mmbutton\" value=\"중고장터\" onclick=\"javascript:location.href='/bookjeok/views/usedshop/UsedAuctionMainView.jsp';\"></td>\n");
      out.write("		<td><input type=\"button\" class=\"mmbutton\" value=\"리뷰\" onclick=\"javascript:location.href='/bookjeok/views/review/ReviewMainView.jsp';\"></td>\n");
      out.write("	</tr>\n");
      out.write("</table>\n");
 } else if (loginUser != null && loginUser.getAdmin().equals("Y")) { 
      out.write("\n");
      out.write("<table class=\"adminmainbar\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("	<tr>\n");
      out.write("		<td><input type=\"button\" class=\"admmbutton\" value=\"회원관리\" onclick=\"javascript:location.href='/bookjeok/ulist.ad';\"></td>\n");
      out.write("		<td><input type=\"button\" class=\"admmbutton\" value=\"상품관리\" onclick=\"javascript:location.href='/bookjeok/bklist.ad';\"></td>\n");
      out.write("		<td><input type=\"button\" class=\"admmbutton\" value=\"장터관리\" onclick=\"javascript:location.href='/bookjeok/usaulist.ad';\"></td>\n");
      out.write("		<td><input type=\"button\" class=\"admmbutton\" value=\"리뷰관리\" onclick=\"javascript:location.href='/bookjeok/rlist.ad';\"></td>\n");
      out.write("		<td><input type=\"button\" class=\"admmbutton\" value=\"공지사항관리\" onclick=\"javascript:location.href='/bookjeok/nlist.ad';\"></td>\n");
      out.write("		<td><input type=\"button\" class=\"admmbutton\" value=\"1:1 문의관리\" onclick=\"javascript:location.href='/bookjeok/alist.ad';\"></td>\n");
      out.write("	</tr>\n");
      out.write("</table>\n");
 } else if (loginUser != null) { 
      out.write("\n");
      out.write("<table class=\"mainbar\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("	<tr>\n");
      out.write("		<td><input type=\"button\" class=\"mmbutton\" value=\"도서\" onclick=\"javascript:location.href='/bookjeok/views/book/PBookMainView.jsp';\"></td>\n");
      out.write("		<td><input type=\"button\" class=\"mmbutton\" value=\"E-Book\" onclick=\"javascript:location.href='/bookjeok/views/book/EBookMainView.jsp';\"></td>\n");
      out.write("		<td><input type=\"button\" class=\"mmbutton\" value=\"오디오북\" onclick=\"javascript:location.href='/bookjeok/views/book/ABookMainView.jsp';\"></td>\n");
      out.write("		<td><input type=\"button\" class=\"mmbutton\" value=\"중고장터\" onclick=\"javascript:location.href='/bookjeok/views/usedshop/UsedAuctionMainView.jsp';\"></td>\n");
      out.write("		<td><input type=\"button\" class=\"mmbutton\" value=\"리뷰\" onclick=\"javascript:location.href='/bookjeok/views/review/ReviewMainView.jsp';\"></td>\n");
      out.write("	</tr>\n");
      out.write("</table>\n");
 } 
      out.write("\n");
      out.write("</center>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

	User auctionloginUser = (User) session.getAttribute("loginUser");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>북적북적</title>\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Serif+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("* { font-family: 'Noto Serif KR', serif; }\r\n");
      out.write(".topmenu input[type=button] {\r\n");
      out.write("	align: center;\r\n");
      out.write("	float: left;\r\n");
      out.write("	width: 300px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	background-color: #8258FA;\r\n");
      out.write("	-webkit-border-radius: 15px;\r\n");
      out.write("	font-size: 16pt;\r\n");
      out.write("	color: white;\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write(".topmenu input[type=submit] {\r\n");
      out.write("	align: center;\r\n");
      out.write("	float: left;\r\n");
      out.write("	width: 300px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	background-color: #8258FA;\r\n");
      out.write("	-webkit-border-radius: 15px;\r\n");
      out.write("	font-size: 16pt;\r\n");
      out.write("	color: white;\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write(".leftmenu {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("}\r\n");
      out.write(".textdiv {\r\n");
      out.write("	align: center;\r\n");
      out.write("	background-color: #8181F7;\r\n");
      out.write("	width: 146px;\r\n");
      out.write("	height: 35px;\r\n");
      out.write("	-webkit-border-radius: 10px;\r\n");
      out.write("	border: 2px solid #5858FA;\r\n");
      out.write("	font-size: 14pt;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding-top: 7px;\r\n");
      out.write("}\r\n");
      out.write(".lmenubutton[type=button] {\r\n");
      out.write("	width: 150px;\r\n");
      out.write("	height: 35px;\r\n");
      out.write("	background-color: #58ACFA;\r\n");
      out.write("	-webkit-border-radius: 10px;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write(".leftmenu {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	left: -375px;\r\n");
      out.write("}\r\n");
      out.write(".leftmenu .catemenu {\r\n");
      out.write("	width: 148px;\r\n");
      out.write("	height: 33px;\r\n");
      out.write("	background-color: #58ACFA;\r\n");
      out.write("	-webkit-border-radius: 10px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	border: 1px solid black;\r\n");
      out.write("}\r\n");
      out.write(".category {\r\n");
      out.write("	width: 150px;\r\n");
      out.write("	height: 35px;\r\n");
      out.write("	background-color: #58ACFA;\r\n");
      out.write("	-webkit-border-radius: 10px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	border: 1px solid black;\r\n");
      out.write("	font-size: 12pt;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write(".catemenu a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write(".leftmenu table tr {\r\n");
      out.write("	margin-top: 0px;\r\n");
      out.write("}\r\n");
      out.write(".newauction {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	background-color: #7B3F3F;\r\n");
      out.write("	border: 3px solid #4C2E2E;\r\n");
      out.write("	-webkit-border-radius: 20px;\r\n");
      out.write("	color: white;\r\n");
      out.write("	font-size: 18pt;\r\n");
      out.write("	width: 180px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	left: 350px;\r\n");
      out.write("	top: -1010px;\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<table cellspacing=\"0\" cellpadding=\"0\" class=\"topmenu\" align=\"center\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><input type=\"button\" value=\"경매 장터\" onclick=\"javascript:location.href='/bookjeok/views/usedshop/UsedAuctionMainView.jsp';\"></td>\r\n");
      out.write("		<td><input type=\"button\" value=\"일반 장터\" onclick=\"javascript:location.href='/bookjeok/views/usedshop/UsedNormalMainView.jsp';\"></td>\r\n");
      out.write("		");
 if(auctionloginUser == null) { 
      out.write("\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("			<form action=\"/bookjeok/views/user/loginPage.jsp\" method=\"get\">\r\n");
      out.write("			<td><input type=\"submit\" name=\"myusedpage\" value=\"내 장터\"></td>\r\n");
      out.write("			</form>\r\n");
      out.write("		");
 }else{ 
      out.write("\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("			<td><input type=\"button\" name=\"myusedpage\" value=\"내 장터\" \r\n");
      out.write("						onclick=\"javascript:location.href='/bookjeok/usaumylist?userid=");
      out.print( auctionloginUser.getUserId() );
      out.write("';\"></td>\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table cellspacing=\"1\" cellpadding=\"0\" align=\"center\" class=\"leftmenu\">\r\n");
      out.write("	<tr><td><div class=\"textdiv\">북적북적</div></td></tr>\r\n");
      out.write("	<tr><td><input class=\"lmenubutton\" type=\"button\" value=\"경쟁 품목\" onclick=\"javascript:location.href='/bookjeok/usauhotlist';\"></td></tr>\r\n");
      out.write("	<tr><td><input class=\"lmenubutton\" type=\"button\" value=\"마감 임박\" onclick=\"javascript:location.href='/bookjeok/usaulastlist';\"></td></tr>\r\n");
      out.write("	<tr><td><div class=\"textdiv\">장르별</div></td></tr>\r\n");
      out.write("	<tr><td><button class=\"category\" onclick=\"javascript:location.href='/bookjeok/usaualllist';\">전체</button></td></tr>\r\n");
      out.write("	<tr><td><button class=\"category\" onclick=\"javascript:location.href='/bookjeok/usaulist?category=1';\">소설</button></td></tr>\r\n");
      out.write("	<tr><td><button class=\"category\" onclick=\"javascript:location.href='/bookjeok/usaulist?category=2';\">장르 소설</button></td></tr>\r\n");
      out.write("	<tr><td><button class=\"category\" onclick=\"javascript:location.href='/bookjeok/usaulist?category=3';\">경제 / 경영</button></td></tr>\r\n");
      out.write("	<tr><td><button class=\"category\" onclick=\"javascript:location.href='/bookjeok/usaulist?category=4';\">자기계발</button></td></tr>\r\n");
      out.write("	<tr><td><button class=\"category\" onclick=\"javascript:location.href='/bookjeok/usaulist?category=5';\">시 / 에세이</button></td></tr>\r\n");
      out.write("	<tr><td><button class=\"category\" onclick=\"javascript:location.href='/bookjeok/usaulist?category=6';\">인문</button></td></tr>\r\n");
      out.write("	<tr><td><button class=\"category\" onclick=\"javascript:location.href='/bookjeok/usaulist?category=7';\">국어 / 외국어</button></td></tr>\r\n");
      out.write("	<tr><td><button class=\"category\" onclick=\"javascript:location.href='/bookjeok/usaulist?category=8';\">역사 / 풍속 / 신화</button></td></tr>\r\n");
      out.write("	<tr><td><button class=\"category\" onclick=\"javascript:location.href='/bookjeok/usaulist?category=9';\">사회 / 정치 / 법</button></td></tr>\r\n");
      out.write("	<tr><td><button class=\"category\" onclick=\"javascript:location.href='/bookjeok/usaulist?category=10';\">코믹스</button></td></tr>\r\n");
      out.write("	<tr><td><button class=\"category\" onclick=\"javascript:location.href='/bookjeok/usaulist?category=11';\">아동</button></td></tr>\r\n");
      out.write("	<tr><td><button class=\"category\" onclick=\"javascript:location.href='/bookjeok/usaulist?category=12';\">유아</button></td></tr>\r\n");
      out.write("	<tr><td><button class=\"category\" onclick=\"javascript:location.href='/bookjeok/usaulist?category=13';\">예술 / 대중문화</button></td></tr>\r\n");
      out.write("	<tr><td><button class=\"category\" onclick=\"javascript:location.href='/bookjeok/usaulist?category=14';\">교재 / 수험서</button></td></tr>\r\n");
      out.write("	<tr><td><button class=\"category\" onclick=\"javascript:location.href='/bookjeok/usaulist?category=15';\">청소년 교양</button></td></tr>\r\n");
      out.write("	<tr><td><button class=\"category\" onclick=\"javascript:location.href='/bookjeok/usaulist?category=16';\">자연과학 / 공학</button></td></tr>\r\n");
      out.write("	<tr><td><button class=\"category\" onclick=\"javascript:location.href='/bookjeok/usaulist?category=17';\">종교 / 역학</button></td></tr>\r\n");
      out.write("	<tr><td><button class=\"category\" onclick=\"javascript:location.href='/bookjeok/usaulist?category=18';\">건강 / 의학</button></td></tr>\r\n");
      out.write("	<tr><td><button class=\"category\" onclick=\"javascript:location.href='/bookjeok/usaulist?category=19';\">북모닝</button></td></tr>\r\n");
      out.write("	<tr><td><button class=\"category\" onclick=\"javascript:location.href='/bookjeok/usaulist?category=20';\">여행 / 취미</button></td></tr>\r\n");
      out.write("	<tr><td><button class=\"category\" onclick=\"javascript:location.href='/bookjeok/usaulist?category=21';\">매거진</button></td></tr>\r\n");
      out.write("	<tr><td><button class=\"category\" onclick=\"javascript:location.href='/bookjeok/usaulist?category=22';\">가정 / 생활 / 요리</button></td></tr>\r\n");
      out.write("	<tr><td><button class=\"category\" onclick=\"javascript:location.href='/bookjeok/usaulist?category=23';\">컴퓨터 / 인터넷</button></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<center>\r\n");
 if(auctionloginUser == null) { 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("	<form action=\"/bookjeok/views/user/loginPage.jsp\" method=\"get\">\r\n");
      out.write("	<input type=\"submit\" class=\"newauction\" name=\"newauction\" value=\"등록하기\"><br>\r\n");
      out.write("	</form>\r\n");
 }else{ 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("	<input type=\"button\" class=\"newauction\" name=\"newauction\" value=\"등록하기\" \r\n");
      out.write("				onclick=\"window.open('/bookjeok/views/usedshop/usedshopAuctionBookSearch.jsp', \r\n");
      out.write("				'searchWindow', 'width=550, height=280, scrollbars=no, resizable=no, status=no, menubar=no, toolbar=no');\"> <br>\r\n");
 } 
      out.write("\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table align=\"center\" width=\"700px\" height=\"180px\" class=\"contentbox\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td class=\"usimg\"><img width=\"100%\" class=\"usimg\" style=\"border: 1px solid #81BEF7; -webkit-border-radius: 5px;\" \r\n");
      out.write("											src=\"/bookjeok/resources/book_img/");
      out.print( usauselect.getBookimg() );
      out.write("\"></td>\r\n");
      out.write("		<td>\r\n");
      out.write("			<table width=\"470px\" height=\"180px\" class=\"usinfo\">\r\n");
      out.write("				<tr><td width=\"120px\"><h3 class=\"eachtitle\">도서명</h3></td>\r\n");
      out.write("					<td colspan=\"3\"><h3 class=\"eachcontent\">");
      out.print( usauselect.getBookNm() );
      out.write("</h3></td></tr>\r\n");
      out.write("				<tr><td width=\"120px\"><h3 class=\"eachtitle\">카테고리</h3></td>\r\n");
      out.write("					<td colspan=\"3\"><h3 class=\"eachcontent\">");
      out.print( usauselect.getBookCategory() );
      out.write("</h3></td></tr>\r\n");
      out.write("				<tr><td width=\"120px\"><h3 class=\"eachtitle\">도서정보</h3></td>\r\n");
      out.write("					<td colspan=\"3\"><h4 class=\"eachcontent\">");
      out.print( usauselect.getAuthor() );
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print( usauselect.getPublisher() );
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print( usauselect.getPublishDate() );
      out.write("</h4></td></tr>\r\n");
      out.write("				<tr><td width=\"120px\"><h3 class=\"eachtitle\">판매자</h3></td>\r\n");
      out.write("					<td><h3 class=\"eachcontent\">");
      out.print( usauselect.getUserWriterId() );
      out.write("</h3></td>\r\n");
      out.write("					<td width=\"120px\"><h3 class=\"eachtitle\">등 급</h3></td>\r\n");
      out.write("					<td><h3 class=\"eachcontent\">");
      out.print( usauselect.getUserRank() );
      out.write("</h3></td></tr>\r\n");
      out.write("				<tr><td width=\"120px\"><h3 class=\"eachtitle\">정 가</h3></td>\r\n");
      out.write("					<td><h3 class=\"eachcontent\">");
      out.print( usauselect.getBookPrice() );
      out.write("</h3></td>\r\n");
      out.write("					<td width=\"120px\"><h3 class=\"eachtitle\">품 질</h3></td>\r\n");
      out.write("					<td><h3 class=\"eachcontent\">");
      out.print( usauselect.getaQuality() );
      out.write("</h3></td></tr>\r\n");
      out.write("				<tr><td width=\"120px\"><h4 class=\"eachtitle\" style=\"padding-top: 3px;\">시작 입찰가</h4></td>\r\n");
      out.write("					<td><h3 class=\"eachcontent\">");
      out.print( usauselect.getStartBid() );
      out.write("</h3></td>\r\n");
      out.write("					<td width=\"120px\"><h4 class=\"eachtitle\" style=\"padding-top: 3px;\">현재 입찰가</h4></td>\r\n");
      out.write("					<td><h3 class=\"eachcontent\">");
      out.print( usauselect.getCurrentBid() );
      out.write("</h3></td></tr>\r\n");
      out.write("				<tr><td width=\"120px\"><h3 class=\"eachtitle\">마감날짜</h3></td>\r\n");
      out.write("					<td colspan=\"3\"><h3 class=\"eachcontent\">");
      out.print( usauselect.getaCloseDate() );
      out.write("</h3></td></tr>\r\n");
      out.write("				");
 if(auctionloginUser != null && auctionloginUser.getUserId().equals(usauselect.getUserWriterId())) { 
      out.write("\r\n");
      out.write("				<tr><td colspan=\"2\" style=\"height: 40px;\"></td></tr>\r\n");
      out.write("				");
 } else if(auctionloginUser != null) { 
      out.write("\r\n");
      out.write("				<tr><td colspan=\"2\" align=\"center\"><input type=\"button\" class=\"ususerbid\" value=\"직접 입찰\" \r\n");
      out.write("							onclick=\"window.open('/bookjeok/usauuserbidview?marketcd=");
      out.print( usauselect.getaMarketCd() );
      out.write("', \r\n");
      out.write("								'bidWindow', 'width=550, height=550, scrollbars=no, resizable=no, status=no, menubar=no, toolbar=no');\"></td>\r\n");
      out.write("					<td colspan=\"2\" align=\"center\"><input type=\"button\" class=\"ussystembid\" value=\"자동 입찰\" \r\n");
      out.write("							onclick=\"window.open('/bookjeok/usausystembidview?marketcd=");
      out.print( usauselect.getaMarketCd() );
      out.write("', \r\n");
      out.write("								'bidWindow', 'width=550, height=550, scrollbars=no, resizable=no, status=no, menubar=no, toolbar=no');\"></td></tr>\r\n");
      out.write("				");
 } 
      out.write("\r\n");
      out.write("			</table>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td colspan=\"2\"><h3 class=\"eachtitle\">상품 소개</h3></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td colspan=\"2\"><h3 class=\"usedintro\">");
      out.print( usauselect.getaUsedBookIntro() );
      out.write("</h3></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	");
 if(auctionloginUser != null) { 
      out.write('\r');
      out.write('\n');
      out.write('	');
 if(auctionloginUser.getUserId().equals(usauselect.getUserWriterId())) { 
      out.write("\r\n");
      out.write("	<tr><td align=\"center\"><input type=\"button\" class=\"ususerbid\" value=\"수정하기\" \r\n");
      out.write("			onclick=\"javascript:location.href='/bookjeok/usauupdateview?marketid=");
      out.print( usauselect.getaMarketCd() );
      out.write("';\"></td>\r\n");
      out.write("	");
 }} 
      out.write("\r\n");
      out.write("		<td><input type=\"button\" class=\"updateend\" value=\"목록\" onclick=\"javascript:history.go(-1);\"></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>북적북적</title>\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Serif+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("* { font-family: 'Noto Serif KR', serif; }\r\n");
      out.write("\r\n");
      out.write("div#footer {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	bottom: 0;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	color: #01DF3A;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("copyright@ict.org &nbsp; 자바,파이썬 기반 빅데이터 플랫폼 개발자 양성과정<br>\r\n");
      out.write("서울시 마포구 서교동 첨단빌딩 7층, TEL : 02-1234-5678, \r\n");
      out.write("FAX : 02-1234-5679\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
